const crypto=require('crypto');
const formTools=require('./fetch-form')._test;

exports.handler=async(event)=>{if(event.httpMethod!=='POST')return reply(405,{error:'Metode tidak diizinkan.'});try{const body=JSON.parse(event.body||'{}'),forcedTermination=body.forcedTermination===true,payload=formTools.decodeExamId(body.id),html=await formTools.fetchHtml(formTools.canonicalViewUrl(payload.formId)),form=formTools.parseGoogleForm(html,payload.formId),metadata=form.submitMetadata;if(!metadata?.fbzx)throw userError('Metadata pengiriman Google Form tidak dapat dibaca. Silakan coba lagi.',502);const answers=body.answers&&typeof body.answers==='object'?body.answers:{},params=new URLSearchParams();let missing=0;
  for(const q of form.questions){if(q.type==='UNSUPPORTED'||q.type==='FILE_UPLOAD')continue;const complete=appendQuestionAnswer(params,q,answers[q.entryId]);if(q.required&&!complete)missing++}
  if(missing&&!forcedTermination)return reply(400,{error:`Masih ada ${missing} pertanyaan wajib yang belum dijawab.`});params.set('fvv',metadata.fvv||'1');params.set('partialResponse',JSON.stringify([null,null,metadata.fbzx]));params.set('pageHistory',metadata.pageHistory||'0');params.set('fbzx',metadata.fbzx);params.set('submissionTimestamp',metadata.submissionTimestamp||'-1');const target=`https://docs.google.com/forms/d/e/${payload.formId}/formResponse`,r=await fetch(target,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'Mozilla/5.0 (compatible; TKAFormRenderer/2.1)'},body:params.toString(),redirect:'manual'}),text=await r.text().catch(()=>'');if(/no longer accepting responses|tidak lagi menerima respons|formulir telah ditutup/i.test(text))throw userError('Google Form sudah ditutup dan tidak menerima respons.',409);if(!(r.status===200||(r.status>=300&&r.status<400))){console.error('Google formResponse rejected',{status:r.status,pageHistory:metadata.pageHistory,hasFbzx:Boolean(metadata.fbzx)});throw userError(`Google menolak pengiriman jawaban (HTTP ${r.status}).`,502)}const submittedAt=new Date().toISOString(),receiptCode=createReceipt(submittedAt);return reply(200,{success:true,forcedTermination,submittedAt,receiptCode,message:'Jawaban Anda telah berhasil dikumpulkan.'})
}catch(err){console.error('submit-form:',err);return reply(err.status||500,{error:err.publicMessage||'Jawaban gagal dikirim. Periksa koneksi lalu coba lagi.'})}};
function userError(message,status=400){const e=new Error(message);e.publicMessage=message;e.status=status;return e}function reply(statusCode,body){return{statusCode,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)}}
function createReceipt(iso){const day=iso.slice(0,10).replace(/-/g,''),random=crypto.randomBytes(4).toString('hex').toUpperCase();return`TKA-${day}-${random}`}
function appendQuestionAnswer(params,q,value){
  if(q.type==='GRID_RADIO'||q.type==='GRID_CHECKBOX'){const state=value&&typeof value==='object'?value:{};let complete=true,any=false;for(const row of q.rows||[]){const raw=state[row.entryId],values=Array.isArray(raw)?raw:[raw],clean=values.filter(v=>typeof v==='string'&&q.options.includes(v));params.append(row.entryId+'_sentinel','');if(row.required&&!clean.length)complete=false;if(clean.length)any=true;for(const item of(q.type==='GRID_RADIO'?clean.slice(0,1):clean))params.append(row.entryId,item)}return q.required?complete:any}
  if(q.type==='DATE'){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const[year,month,day]=value.split('-');params.append(q.entryId+'_month',String(Number(month)));params.append(q.entryId+'_day',String(Number(day)));if(q.dateIncludesYear!==false)params.append(q.entryId+'_year',year);return true}
  if(q.type==='TIME'){if(typeof value!=='string'||!/^\d{2}:\d{2}$/.test(value))return false;const[hour,minute]=value.split(':');params.append(q.entryId+'_hour',String(Number(hour)));params.append(q.entryId+'_minute',String(Number(minute)));return true}
  if(q.type==='DURATION'){const state=value&&typeof value==='object'?value:{},hour=cleanUnit(state.hour),minute=cleanUnit(state.minute),second=cleanUnit(state.second);if(hour===''&&minute===''&&second==='')return false;params.append(q.entryId+'_hour',hour||'0');params.append(q.entryId+'_minute',minute||'0');params.append(q.entryId+'_second',second||'0');return true}
  const values=(Array.isArray(value)?value:[value]).filter(v=>typeof v==='string'&&v.trim()!=='').map(v=>v.trim()),choice=['RADIO','CHECKBOX','LINEAR','RATING'].includes(q.type),restricted=choice||q.type==='DROPDOWN',clean=restricted?values.filter(v=>q.options.includes(v)):values;if(choice)params.append(q.entryId+'_sentinel','');for(const item of clean)params.append(q.entryId,item);return clean.length>0
}
function cleanUnit(value){if(value===null||value===undefined||value==='')return'';const number=Math.max(0,Math.floor(Number(value)));return Number.isFinite(number)?String(number):''}
exports._test={createReceipt,appendQuestionAnswer,cleanUnit};
